// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL01B2-c9nZLO-dbdirzihlPs-CQuV_hk',
    appId: '1:54802271372:web:d2d49010014a46f992bfa9',
    messagingSenderId: '54802271372',
    projectId: 'dosawala-4dd6c',
    authDomain: 'dosawala-4dd6c.firebaseapp.com',
    storageBucket: 'dosawala-4dd6c.appspot.com',
    measurementId: 'G-P7CZT8L6W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0B70U9viAeT_j1N68rpvUL20RUkK6nU',
    appId: '1:54802271372:android:4db7047e1c11e33192bfa9',
    messagingSenderId: '54802271372',
    projectId: 'dosawala-4dd6c',
    storageBucket: 'dosawala-4dd6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1mv9c24TxYsFd4soU5JbXJ928h2pJ4o',
    appId: '1:54802271372:ios:a64954ce167c928692bfa9',
    messagingSenderId: '54802271372',
    projectId: 'dosawala-4dd6c',
    storageBucket: 'dosawala-4dd6c.appspot.com',
    iosBundleId: 'com.example.dosaWala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm1mv9c24TxYsFd4soU5JbXJ928h2pJ4o',
    appId: '1:54802271372:ios:e9e2ebe46b42f75292bfa9',
    messagingSenderId: '54802271372',
    projectId: 'dosawala-4dd6c',
    storageBucket: 'dosawala-4dd6c.appspot.com',
    iosBundleId: 'com.example.dosaWala.RunnerTests',
  );
}
